body:
  - type: textarea
    id: attachments
    attributes:
      label: "Attachments"
      description: Please add associated attachments (if any)
      placeholder: Please add associated attachments (if any)
    validations:
      required: false
